#!/bin/sh

pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
pip install dataserv-client
ln -s /opt/driveshare/driveshare /usr/local/bin/driveshare
