convert -strip btndown_borderimage.png btndown_borderimage.png
convert -strip btn_borderimage.png btn_borderimage.png
convert -strip dropdown.png dropdown.png
convert -strip favicon2.png favicon2.png
convert -strip qmark.png qmark.png
convert -strip qmarkdown.png qmarkdown.png
convert -strip trans_btndown_borderimage.png trans_btndown_borderimage.png
convert -strip trans_btndown_borderimage_left.png trans_btndown_borderimage_left.png
convert -strip trans_btndown_borderimage_left2.png trans_btndown_borderimage_left2.png
convert -strip trans_btndown_borderimage_right.png trans_btndown_borderimage_right.png
convert -strip trans_btndown_borderimage_right2.png trans_btndown_borderimage_right2.png
convert -strip trans_btn_borderimage.png trans_btn_borderimage.png
convert -strip trans_btn_borderimage_left.png trans_btn_borderimage_left.png
convert -strip trans_btn_borderimage_left2.png trans_btn_borderimage_left2.png
convert -strip trans_btn_borderimage_right.png trans_btn_borderimage_right.png
convert -strip trans_btn_borderimage_right2.png trans_btn_borderimage_right2.png
convert -strip triangle.png triangle.png